In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('song_data_final.csv')
print(df.shape)
df.head()

(1995, 46)

,Unnamed: 0,Title,Artist,Top Genre,Year,BPM,Energy,Danceability,Loudness_db,Liveness,...,Genre_latin,Genre_mellow gold,Genre_metal,Genre_opera,Genre_pop,Genre_punk,Genre_reggae,Genre_rock,Genre_singer-songwriter,Genre_soul
0,0,Sunrise,Norah Jones,pop,2004,157,30,53,-14,11,...,0,0,0,0,1,0,0,0,0,0
1,1,Black Night,Deep Purple,rock,2000,135,79,50,-11,17,...,0,0,0,0,0,0,0,1,0,0
2,2,Clint Eastwood,Gorillaz,hip hop/rap,2001,168,69,66,-9,7,...,0,0,0,0,0,0,0,0,0,0
3,3,The Pretender,Foo Fighters,alternative,2007,173,96,43,-4,3,...,0,0,0,0,0,0,0,0,0,0
4,4,Waitin' On A Sunny Day,Bruce Springsteen,rock,2002,106,82,58,-5,10,...,0,0,0,0,0,0,0,1,0,0

In [3]:
df.describe()

,Unnamed: 0,Year,BPM,Energy,Danceability,Loudness_db,Liveness,Valence,Duration,Acousticness,...,Genre_latin,Genre_mellow gold,Genre_metal,Genre_opera,Genre_pop,Genre_punk,Genre_reggae,Genre_rock,Genre_singer-songwriter,Genre_soul
count,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,...,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000,1995.000000
mean,997.000000,1992.980451,120.240602,59.666667,53.224060,-9.012030,19.009524,49.402506,262.537343,28.883709,...,0.001504,0.005514,0.003008,0.001003,0.199499,0.002506,0.006015,0.413534,0.004010,0.025063
std,576.051213,16.121720,28.043226,22.156226,15.360673,3.650319,16.723559,24.853531,93.675077,29.027302,...,0.038759,0.074068,0.054772,0.031654,0.399724,0.050012,0.077342,0.492590,0.063214,0.156355
min,0.000000,1956.000000,37.000000,3.000000,10.000000,-27.000000,2.000000,3.000000,93.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,498.500000,1979.000000,99.000000,42.000000,43.000000,-11.000000,9.000000,29.000000,212.000000,3.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,997.000000,1993.000000,119.000000,61.000000,53.000000,-8.000000,12.000000,47.000000,245.000000,18.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1495.500000,2007.000000,136.000000,78.000000,64.000000,-6.000000,23.000000,69.500000,289.500000,50.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,1994.000000,2019.000000,206.000000,100.000000,96.000000,-2.000000,99.000000,99.000000,1412.000000,99.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
X = df.drop(columns=['Title','Artist','Top Genre'], axis=1)

y = df['Popularity']
y[y == 2] = 0
y[y == 1] = 1

In [20]:
import xgboost as xgb
data_dmatrix = xgb.DMatrix(data=X,label=y)

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [23]:
from xgboost import XGBClassifier

# declare parameters
params = {
            'objective':'binary:logistic',
            'max_depth': 4,
            'alpha': 10,
            'learning_rate': 1.0,
            'n_estimators':100
        }
            
# instantiate the classifier 
xgb_clf = XGBClassifier(**params)

# fit the classifier to the training data
xgb_clf.fit(X,y)

XGBClassifier(alpha=10, base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1.0, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', ...)

In [29]:
y_pred = xgb_clf.predict(X)
from sklearn.metrics import accuracy_score

print('XGBoost model accuracy score: {0:0.4f}'. format(accuracy_score(y, y_pred)))

XGBoost model accuracy score: 0.9023

XGBoost: XGBoost is a gradient boosting algorithm that has gained popularity in recent years due to its high accuracy and efficiency. It can help you build a model that predicts a song's popularity based on the audio features and can identify the most important features that contribute to a song's success.